### model
model_name_or_path: /home/models/llama3-8b

### 手动配置区
template: llama3 # 重要！模板
adapter_name_or_path: /home/wma/Mercury-SQL/Models/llama3B/lr_sft/SPIDER_80/checkpoint-1500
output_dir: ../Results/prediction/lr_sft/llama3B/spider/80
eval_dataset: SPIDER_low_resource_EVAL

# 统一参数区
cutoff_len: 2048
dataset_dir: data
do_predict: true
finetuning_type: lora
flash_attn: auto
max_new_tokens: 200
max_samples: 100000
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bitsandbytes
stage: sft
top_p: 0.9
temperature: 0.6