model_name_or_path: /home/models/Llama-3.2-3B
eval_dataset: C3_orig_eval_1_hop
cutoff_len: 1024
max_samples: 10000
do_predict: true
template: default
overwrite_cache: true
preprocessing_num_workers: 16
### output
flash_attn: auto                          # 自动选择attention
max_new_tokens: 100
output_dir: ../Results/prediction/default
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 8
predict_with_generate: true
ddp_timeout: 180000000