### model
model_name_or_path: /home/models/Llama-3.2-3B
adapter_name_or_path: /home/wma/Mercury-SQL/Models/llama3B/C3_orig_train_1_hop_lr_5                                   # 选择最佳的checkpoint


output_dir: ../Results/prediction/C3_orig_eval_1_hop                                               # 输出目录
cutoff_len: 1024
dataset_dir: data
do_predict: true
eval_dataset: C3_orig_eval_1_hop
finetuning_type: lora
flash_attn: auto
max_new_tokens: 50
max_samples: 100000
per_device_eval_batch_size: 8
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bitsandbytes
stage: sft
temperature: 0.95
template: default
top_p: 0.7
