### model
model_name_or_path: /home/models/Llama-3.2-3B
adapter_name_or_path:                                     # 选择最佳的checkpoint


### method
stage: sft
do_predict: true
finetuning_type: lora

### dataset
eval_dataset:                                              # 批量推理数据集
template: llama3
cutoff_len: 1024
max_samples: 50
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ../Results/prediction/                                               # 输出目录
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 1
predict_with_generate: true
ddp_timeout: 180000000
