### model
model_name_or_path: /home/models/Llama-3.2-3B

### 手动配置区
template: llama3 # 重要！模板
adapter_name_or_path: /home/wma/Mercury-SQL/Models/llama3B/tp_llama3/C3_train_1_hop/checkpoint-980
output_dir: ../Results/prediction/tp_llama/C3
eval_dataset: C3_eval_1_hop

# 统一参数区
cutoff_len: 1024
dataset_dir: data
do_predict: true
finetuning_type: lora
flash_attn: auto
max_new_tokens: 100
max_samples: 100000
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bitsandbytes
stage: sft
top_p: 0.7
temperature: 0.95