### model
model_name_or_path: /home/models/Llama-3.2-3B

### 手动配置区
template: llama3 # 重要！模板
output_dir: ../Results/prediction/lr_sft/spider/20
eval_dataset: SPIDER_low_resource_EVAL

# 统一参数区
cutoff_len: 2048
dataset_dir: data
do_predict: true
flash_attn: auto
max_new_tokens: 200
max_samples: 100000
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bitsandbytes
top_p: 0.9
temperature: 0.6