### model
model_name_or_path: /home/models/Llama-3.2-3B

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: DTS_train_1of2_hop  #需更改的参数，数据集
template: default       #采用default模版
cutoff_len: 1024
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ../Models/llama3B/tp_default/DTS_train_1of2_hop # 需更改的参数
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 100
