### model
model_name_or_path: /home/models/Llama-3.2-3B

### 手动配置区
template: default # 重要！模板
adapter_name_or_path: /home/wma/Mercury-SQL/Models/llama3B/tp_llama3/DTS_train_1of2_hop/checkpoint-1200
output_dir: ../Results/prediction/tp_default/DTS-sl
eval_dataset: DTS_eval_1of2_hop

# 统一参数区
cutoff_len: 1024
dataset_dir: data
do_predict: true
finetuning_type: lora
flash_attn: auto
max_new_tokens: 1000
max_samples: 100000
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bitsandbytes
stage: sft
top_p: 0.7
temperature: 0.95